baseURL = 'https://rajhiray.github.io/'
languageCode = 'en-us'
title = 'Raj Hiray'
theme = "github-style"
lastmod = true
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
[params]
  author = "Raj Hiray"
  #description = "In solitude, where we are least alone."
  description = "Think Twice Code Once ..."
  github = "rajhiray"
  #facebook = "MeiK2333"
  #twitter = "MeiK2333"
  linkedin = "raj-hiray"
  #instagram = "MeiK2333"
  email = "raj.hiray@outlook.com"
  url = "https://rajhiray.github.io/"
  #keywords = "blog, google analytics"
  #rss = true
  lastmod = true
  userStatusEmoji = "😈"
  favicon = "/images/github.png"
  avatar = "/images/avatar0.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "India"
  enableGitalk = true